version: '3.8'
services:

# =============================================>> DB
  db:
    image: postgres:12.4-alpine
    container_name: pos-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pos-db
    healthcheck:
      test: mysqladmin ping --protocol=tcp --password=pass --silent
      interval: 5s
      retries: 4
    volumes:
    # Backup Data in pos-db
      - ./pos-db:/var/lib/postgresql/data
    networks:
      - project
# =============================================>> POS API
  java-api:
    container_name: pos-api
    build:
      context: ./api-v1/.
      dockerfile: Dockerfile
    # command: ["sleep","infinity"]
    volumes:
      - ./api-v1/src:/opt/pos/src
    ports:
      - 8081:8081
    environment:
      DB_CONNECTION: postgresql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: pos-db
      DB_USERNAME: root
      DB_PASSWORD: secret
    networks:
      - project
networks:
  project:
    driver: bridge